### ISSUE TITLE
Can't mount the mount... 

### ISSUE THREAD

**Issue by maooam27** [vKolerts/quest-sidenoder#17]
![Immagine 2021-08-01 120807](https://user-images.githubusercontent.com/52970070/127767117-6d622280-3cb4-4823-8a7e-ff7505bd7d0e.png)
If you cannot translate (that's italian) it says: 
- Cannot mount, only one socket bind is allowed, or something similar... pls could you fix?

**Comment by vKolerts** [comment]
> ![Immagine 2021-08-01 120807](https://user-images.githubusercontent.com/52970070/127767117-6d622280-3cb4-4823-8a7e-ff7505bd7d0e.png)
> If you cannot translate (that's italian) it says:
> 
>     * Cannot mount, only one socket bind is allowed, or something similar... pls could you fix?

try manualy delete C:/Users/mfede/AppData/Local/Temp/mnt folder and reboot your PC

**Comment by Berniep1** [comment]
If this does not help, maybe another program block port 5572.
I my case it was "videostream", I uninstalled & rebooted, now all is fine.

**Comment by coop1661** [comment]
![Capture](https://user-images.githubusercontent.com/85299740/130264912-21a7b5df-bb31-4f2b-af2e-9081edab3621.PNG)

**Comment by coop1661** [comment]
please help, I already tried looking if some app is blocking the port but the only thing i saw that rclone is using the port as needed

**Comment by coop1661** [comment]
please help, I already tried looking if some app is blocking the port but the only thing i saw that rclone is using the port as needed

**Comment by vKolerts** [comment]
Please do this steps: 
1) restart application
2) try remount on fail(click mount button at right top corner) 
3) send me a log /{USER_PATH}/sidenoder/debug_last.log

**Comment by totalitarian** [comment]
{
  platform: 'win',
  arch: 'x64',
  version: '0.6.0',
  sidenoderHome: 'C:/Users/Lee/sidenoder'
} win32 x64 [
  'C:\\Users\\Lee\\AppData\\Local\\Programs\\sidenoder\\sidenoder.exe'
] 
icons list loaded 
kmetas loaded 
check_deps received adb 
checkDeps() 
check_deps received rclone 
checkDeps() 
{ cmd: 'C:\\Users\\Lee\\sidenoder\\rclone.exe --version' } 
check_deps received zip 
checkDeps() 
{ cmd: 'C:\\Users\\Lee\\sidenoder\\7za.exe --help | findstr  "7-Zip"' } 
check_deps received scrcpy 
checkDeps() 
{
  cmd: 'C:\\Users\\Lee\\Downloads\\scrcpy-win64-v1.18\\scrcpy.exe --version'
} 
exec_stdout C:\Users\Lee\sidenoder\7za.exe --help | findstr  "7-Zip" 7-Zip (a) 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
 
7-Zip (a) 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
 
change_config received { key: 'donShown', val: true } 
cfg.update donShown true 
ERROR: exec_stderr C:\Users\Lee\Downloads\scrcpy-win64-v1.18\scrcpy.exe --version scrcpy 1.18

dependencies:
 - SDL 2.0.14
 - libavcodec 58.91.100
 - libavformat 58.45.100
 - libavutil 56.51.100
 
{ cmd: 'C:\\Users\\Lee\\sidenoder\\adb.exe start-server' } 
exec_stdout C:\Users\Lee\sidenoder\rclone.exe --version rclone v1.55.1
- os/type: windows
- os/arch: amd64
- go/version: go1.16.3
- go/linking: dynamic
- go/tags: cmount
 
checkMount() 
Current version: 0.6.0 
Github version: undefined 
start rclone 
ERROR: exec_stderr C:\Users\Lee\sidenoder\adb.exe start-server * daemon not running; starting now at tcp:5037
* daemon started successfully
 
{ cmd: 'C:\\Users\\Lee\\sidenoder\\adb.exe --version' } 
exec_stdout C:\Users\Lee\sidenoder\adb.exe --version Android Debug Bridge version 1.0.41
Version 31.0.2-7242960
Installed as C:\Users\Lee\sidenoder\adb.exe
 
trackDevices() 
{ devices: [] } 
{ devices: [] } 
{ devices: [] } 
ERROR: rclone error: Error: Command failed: "C:\Users\Lee\sidenoder\rclone.exe" mount --read-only --rc --rc-no-auth --config="C:\Users\Lee\sidenoder\rclone.conf" VRP_mirror06: "C:/Users/Lee/AppData/Local/Temp/mnt"
2021/09/10 19:35:11 NOTICE: Serving remote control on http://localhost:5572/
Cannot create WinFsp-FUSE file system: mount point in use.
2021/09/10 19:35:11 ERROR : Google drive root '': Mount failed
2021/09/10 19:35:11 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '"C:\\Users\\Lee\\sidenoder\\rclone.exe" mount --read-only --rc --rc-no-auth --config="C:\\Users\\Lee\\sidenoder\\rclone.conf" VRP_mirror06: "C:/Users/Lee/AppData/Local/Temp/mnt"'
} 
{ devices: [] } 
checkMount() 
checkMount() 
start rclone 
ERROR: rclone error: Error: Command failed: "C:\Users\Lee\sidenoder\rclone.exe" mount --read-only --rc --rc-no-auth --config="C:\Users\Lee\sidenoder\rclone.conf" VRP_mirror06: "C:/Users/Lee/AppData/Local/Temp/mnt"
2021/09/10 19:35:30 NOTICE: Serving remote control on http://localhost:5572/
Cannot create WinFsp-FUSE file system: mount point in use.
2021/09/10 19:35:31 ERROR : Google drive root '': Mount failed
2021/09/10 19:35:31 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '"C:\\Users\\Lee\\sidenoder\\rclone.exe" mount --read-only --rc --rc-no-auth --config="C:\\Users\\Lee\\sidenoder\\rclone.conf" VRP_mirror06: "C:/Users/Lee/AppData/Local/Temp/mnt"'
} 
checkMount()

**Comment by totalitarian** [comment]
Fixed it by deleting C:/Users/Lee/AppData/Local/Temp/mnt
